# TEMPLATE TYPE
type Template {
	_id: ID!
	name: String!
	exercises: [SessionExercise]
	notes: String
	creator: User
}

# INPUTS
input TemplateInput {
	_id: ID
	name: String!
	exercises: [SessionExerciseInput]
	notes: String
}

# ROOT
type Query {
	getTemplateById(templateId: ID!): Template
	getAllTemplates: [Template]
}

type Mutation {
	saveTemplate(templateData: TemplateInput!): Template!
	deleteTemplate(templateId: ID!): Boolean
}
