type User {
	netlifyId: ID!
	exercises: [UserExercise!] @relation(name: "user_exercises")
	sessions: [Session!] @relation(name: "user_sessions")
}

type UserExercise {
	creator: User! @relation(name: "user_exercises")
	name: String!
	history: [Exercise] @relation(name: "exercise_history")
}

type Session {
	creator: User! @relation(name: "user_sessions")
	name: String!
	date: Date!
	performances: [Performance] @relation(name: "session_performance")
	bodyweight: Weight
}

type Performance {
	session: Session @relation(name: "session_performance")
	exercise: [Exercise] @relation(name: "performance_exercise")
}

type Exercise {
	performance: Performance @relation(name: "performance_exercise")
	movement: UserExercise! @relation(name: "exercise_history")
	executions: [Execution]
	date: Date!
}

type Execution @embedded {
	sets: Int
	reps: Int
	duration: Duration
	load: Weight
}

type Weight @embedded {
	amount: Float
	unit: String
}

type Duration @embedded {
	amount: Float
	unit: String
}

type Query {
	getUserById(netlifyId: ID!): User
	getSessionsByName(name: String!): [Session]
}
